language: python
python:
  - "2.7"
  - "3.6"
install:
  - "sudo apt-get install pylint"
  - "sudo apt-get install python-flake8"
script:
  - flake8 phonedaemon/*.py
  - pylint phonedaemon/modules/*.py
